name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bits: [64, 32]
    steps:
    - uses: actions/checkout@v4
    - name: Install 32-bit deps
      if: ${{ matrix.bits == '32' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc-i686-linux-gnu
    - name: Build
      run: |
        if [ "${{ matrix.bits }}" = "32" ]; then
          sh scripts/makeall.sh all BITS=32 CROSS_PREFIX=i686-linux-gnu-
        else
          sh scripts/makeall.sh all
        fi
    - name: Build Chicken Scheme port
      run: |
        if command -v csc >/dev/null 2>&1; then
          csc -o ports/chicken/bcplc-chicken ports/chicken/main.scm
        fi
    - name: Test utilities
      run: |
        if [ "${{ matrix.bits }}" = "32" ]; then
          make -C tools BC=../src/bcplc test
        else
          make -C tools test
        fi
      run: make -C tools test

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure, build and install
      run: |
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr/local
        cmake --build build
        cmake --install build
    - name: Test utilities (CMake)
      run: make -C tools BC=build/src/bcplc test

